image: alpine:latest

getdata:
  stage: build
  script:
  - apk add python
  - apk add nodejs
  - node character.js
  - python update_static.py
  artifacts:
    paths:
    - public

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master