stages:
  - build
  - deploy

image: ubuntu:latest

include: '.build-template.yml'

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
    - mkdir public
    - cp lib/public/* public
  artifacts:
    paths:
      - public
  only:
    - master
