stages:
  - build
  - post

image: ubuntu:latest

include: '.build-template.yml'

post:
  stage: post
  script:
    - apt-get update -y
    - apt-get install -qy python3 python3-pip
    - cd bots/
    - pip3 install -r requirements.txt
    - python3 tweet.py
    - echo 'Successfully tweeted from @hibianime!'
    - python3 toot.py
    - echo 'Successfully tooted from @hibianime@botsin.space!'
  only:
    - social-bots
  except:
    - pushes
