stages:
  - build
  - deploy

image: ubuntu:latest

include: '.build-template.yml'

pages:
  stage: deploy
  script:
    - echo 'Nothing to do...'
  artifacts:
    paths:
      - public
  only:
    - master
