image: alpine:latest

getdata:
  stage: build
  script:
  - apk add nodejs
  - apk add npm
  - npm install markdown-it
  - npm install crypto-js
  - npm install node-fetch
  - node character.js
  - python3 update_static.py
  artifacts:
    paths:
    - public
  only:
  - master

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master