stages:
  - build
  - post

image: ubuntu:latest

include: '.build-template.yml'

tweet:
  stage: post
  script:
    - apt-get update -y
    - apt-get install -qy python3 python3-pip
    - pip3 install -r ./bots/requirements.txt
    - python3 ./bots/tweet.py
    - echo 'Successfully tweeted from @hibianime!'
    - python3 ./bots/toot.py
    - echo 'Successfully tooted from @hibianime@botsin.space!'
  only:
    - social-bots
  except:
    - pushes
