image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

getdata:
  stage: build
  script:
  - npm install
  - node character.js
  - python update_static.py
  artifacts:
    paths:
    - node_modules/
    - public
  only:
  - master

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master