image: ubuntu:latest

getdata:
  stage: build
  script:
  - apt-get update
  - apt-get upgrade
  - Y
  - apt-get install nodejs
  - apt-get install npm
  - apt-get install python3
  - npm install markdown-it
  - npm install crypto-js
  - npm install node-fetch
  - node character.js
  - python update_static.py
  artifacts:
    paths:
    - public
  only:
  - master

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master